### ISSUE TITLE
I can't import LEED 1301

### ISSUE THREAD

**Issue by WandererProgrammer** [iqfareez/albiruni#10]
for sem 3 LEED 1301 from CELPAD is not showing

**Comment by iqfareez** [comment]
Hi @WandererProgrammer, which section?

![image](https://github.com/user-attachments/assets/22dd814b-31df-470f-b0f0-de6ad0cf3a95)

**Comment by WandererProgrammer** [comment]
section 12 can't get subject info

**Comment by 2217441** [comment]
![Screenshot_20240804-093204.png](https://github.com/user-attachments/assets/78bb6f5a-2d99-4fc9-b94c-32a5dab6ff21)

**Comment by iqfareez** [comment]
Thank you guys. After triaging, I found out that the app fails to parse the Day format ('TWTH'). Will fix it soon. Moving this issue to albiruni package.

**Comment by iqfareez** [comment]
Related to #8
